version: "3.8"

networks:
  logging:
    driver: bridge

volumes:
  loki-storage:

services:
  app-python:
    image: alekseikureikin/my-python-app:latest
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - logging

  app-go:
    image: alekseikureikin/my-go-app:latest
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - logging

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-storage:/loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - logging

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_FEATURE_TOGGLES_ENABLE: "alertingQueryAndExpressionsStepMode,alertingSimplifiedRouting"
    volumes:
      - ./grafana-config/datasources:/etc/grafana/provisioning/datasources:ro
    restart: unless-stopped
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - logging
